### PR TITLE
form listeners added

### PR DESCRIPTION
**Pull request by LauraK0**
Relates #1

### CODE REVIEW

**Comment by nataliarusu** [comment]
could you please make sure the form is not submitted if a user fills the input with spaces

**Comment by nataliarusu** [comment]
there is an issue when a user submits an incorrect field. The page alerts about the issue and then resets all fields. It also removes the focus from the form section which makes the user scroll back through the entire page.

**Comment by LauraK0** [comment]
> could you please make sure the form is not submitted if a user fills the input with spaces

Hi Natalia, I did not add validation to the input as it is not a mandatory field as set out in the user story, these were "name", "company name", and "email address". I have added it now.

**Comment by LauraK0** [comment]
> there is an issue when a user submits an incorrect field. The page alerts about the issue and then resets all fields. It also removes the focus from the form section which makes the user scroll back through the entire page.

Thanks for highlighting, latest commits should resolve the issue.

**Review by konstantinakatmada — COMMENTED** [review]
Awesome

**Pull request merged**
